<a href="https://colab.research.google.com/github/suyashchaudhari1821/colab/blob/main/109_Suyash_chaudhari.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
                                                 # Numbers
a=25
print("a as int:",a)
b=548468
print("b as long",b)
c=14.25
print("c as float",c)
d=3.14j
print("d as complex",d)

#string
str1 = "Welcome to Python"
print(str1)

#List
# Represents with sqaure bracket []
# Array is static and list is dynamic
# Can have dissimilar data types
l1=[15,25.6,"Python"]
print(l1)

#tuple
#Represented by ()
#Set of values separated by commas
#list [] and tuple()
#List allows updates in size and elements where as tuple does not allow
#tuple is read only entity
t1=(21,"Python",21.45)
print(t1)

#Dictonary
#Array,Tuple,List we have to remember the index numbers of an element
#Dictionary creates its own index numbers for our elements
d1={"Aradhana":21,"Prarthana":22,"Rugved":23}
print(d1)

a as int: 25
b as long 548468
c as float 14.25
d as complex 3.14j
Welcome to Python
[15, 25.6, 'Python']
(21, 'Python', 21.45)
{'Aradhana': 21, 'Prarthana': 22, 'Rugved': 23}


In [ ]:
#Short hand if-else
print("Enter any number")
num=int(input())
print(num,"is even") if num%2==0 else print(num,"is odd")


Enter any number
3
3 is odd


In [ ]:
#elif
weather = input("What is the Wheather today?") #input
if weather == "Sunny" :
  print("It is a great day to go for a picnic! ")
elif weather == "Cloudy":
  print("Don't forgert to bring jacket in case it rains.")
elif weather=="Rainy":
  print("Remember to bring umbrella")
else:
  print("Sorry! I don't understand the weather condition")


What is the Wheather today?Cloudy
Don't forgert to bring jacket in case it rains.


In [ ]:
i=1
while i<10:
  print("Welcome")
  i=i+1

In [ ]:
print("Enter a value")
num =int(input())
sum=0
i=1
while i<=num:
  sum=sum+i
  i=i+1
  print("sum",sum)

Enter a value
sum 1
sum 3
sum 6
sum 10
sum 15
sum 21
sum 28
sum 36
sum 45
sum 55
sum 66
sum 78
sum 91
sum 105
sum 120
sum 136
sum 153
sum 171
sum 190
sum 210
sum 231


In [ ]:
l1=["C++","java","Python"]
for i in l1:
  print("loop refers to book",i)

loop refers to book C++
loop refers to book java
loop refers to book Python


In [ ]:
def sayHello():
  print("Welcome to Python")
sayHello()

Welcome to Python


In [ ]:
def even():
  print("Enter a number:")
  num = int(input())
  if num%2==0:
    print("Number is even:",num)
  else:
    print("Number is odd:",num)
even()

In [ ]:
def Sum():
  a=5
  b=7
  sum=a+b
  print("Sum =",sum)
Sum()

In [ ]:
l1=["","",""]
l2=["a","",""]
l3=[True,True]
l4 = [True,False]
l5 = [False,False]
a=all(l1)
b=all(l2)
c=all(l3)
d=all(l4)
e=all(l5)
print(a)
print(b)
print(c)
print(d)
print(e)


In [ ]:
def Bill():
  p1 = int(input())
  p2 = int(input())
  p3 = int(input())
  p4 = int(input())
  sum = p1+p2+p3+p4
  print("The Total price of all products = ",sum)
Bill()

In [ ]:
def Marksheet():
  print("Enter marks (0-300)")
  physics = int(input())
  chemistry = int(input())
  math = int(input())
  Total_Marks = physics + chemistry + math
  if (Total_Marks>=30 and Total_Marks<=300 ):
    print("Pass")
  else:
    print("fail")

In [ ]:
l1 = [10,20,"Python",94.2,314]
l1.append(21)
print(l1)

In [ ]:
l1 =["Python", "Java", "Essentials of data science"]
print(l1)
l1.insert(2,"Hadoop")
print(l1)


In [ ]:
#extend() This function adds the elements of parameter list with invoking list
# list1.extends (list2)
l1=[10, 20, 30]
l2=[15,35,45,55]
l1.extend(l2)
print (l1)

In [ ]:
l1= [485,21.344, "Python", 25678]
a = l1.__len__()      #Function returns the length of list
print(a)

In [ ]:
#Statistics, in general, is the method of collection of data, tabulation, and interpretation
import statistics
l1= [1,2,3,3,2,2,2,1]
print(statistics.mean(l1))

In [ ]:
#It is the middle value of the data set. It splits the data into two halves.
import statistics
t1= (21,23,45,67)
print(statistics.median(t1))

In [ ]:
#The median_low() function returns the median of data in case of odd number of elements,
#but in case of even number of elements, returns the lower of two middle elements.
#The statistics.median_low() method calculates the low median of the given data set.
#This method also sorts the data in ascending order before calculating the low median.
import statistics
set1 = [1, 2, 8, 4, 5]
#1,1,2,4,5,8
print("Low Median of the set is", (statistics.median_low (set1)))

In [ ]:
#median_high()
#function returns the median of data in case of odd number of elements,
#but in case of even number of elements, returns the higher of two middle elements.
#median_high() method calculates the high median of the given data set.
#This method also sorts the data in ascending order before calculating the high median.
import statistics
set1= [1, 3, 3, 4, 5]
#1,3,3,4,5
print("Median of the set is", (statistics.median_high(set1)))

In [ ]:
#Mode
#It is the value that has the highest frequency in the given data set.
#The data set may have no mode if the frequency of all data points is the same.
from statistics import mode
t1 = (6, 6, 6,6,3, 3,3,3,3,3,3,3,3,3,3,3,3,4, 5, 5, 5, 5,7)
print("Mode of data set is ", (mode (t1)))

In [ ]:
#The difference between the largest and smallest data point in our data set is known as th
#Range = Largest data value - smallest data value
arr = [1, 2, 3, 4, 5]
Maximum = max(arr)
Minimum= min (arr)
Range = Maximum-Minimum
print("Maximum ={}, Minimum = {} and Range = {}".format (Maximum, Minimum, Range))

In [ ]:
#It is defined as an average squared deviation from the mean.
from statistics import variance
t1=(1, 2, 5, 4, 8, 9, 12)
print("Variance of Samplel is s", (variance(t1)))

In [ ]:
#standard deviation
#It is defined as the square root of the variance.
#It is calculated by finding the Mean, then subtracting each number from the Mean which is
from statistics import stdev
s1=(1, 2, 5, 4, 8, 9, 12)
print("The Standard Deviation of Samplel is s", (stdev(s1)))

In [ ]:
import pandas as pd
df = pd.read_excel('')

In [ ]:
import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/Emp.xlsx')
display(df)
df1= pd.read_excel('/content/drive/MyDrive/sal.xlsx')
display(df1)


Unnamed: 0 Unnamed: 1 Unnamed: 2           Unnamed: 3 Unnamed: 4
0      Sr no.   Emp Name     Emp id                 Date     Leaves
1           1    Ganesh        1001  2023-01-21 00:00:00          2
2           2     Kartik       1002  2023-01-22 00:00:00          4
3           3      Veera       1003  2023-01-23 00:00:00          8
4           4  Sanskruti       1004  2023-01-24 00:00:00          6
5           5    Archana       1005  2023-01-25 00:00:00          1
6           6   Aradhana       1006  2023-01-26 00:00:00          2
7           7    Pratham       1007  2023-01-27 00:00:00          3
8           8     Sayali       1008  2023-01-28 00:00:00          5
9           9     Smruti       1009  2023-01-29 00:00:00          9
10         10      Vijay       1010  2023-01-30 00:00:00          7

Emp Name  Emp id  Salary
0    Ganesh     1001   25000
1     Kartik    1002   40000
2      Veera    1003   80000
3  Sanskruti    1004   60000
4    Archana    1005   50000
5   Aradhana    1006   30000
6    Pratham    1007   15000
7     Sayali    1008   55000
8     Smruti    1009   80000
9      Vijay    1010  100000

In [ ]:
import pandas as pa
df1.sort_values(by=["Salary"])

Emp Name  Emp id  Salary
6    Pratham    1007   15000
0    Ganesh     1001   25000
5   Aradhana    1006   30000
1     Kartik    1002   40000
4    Archana    1005   50000
7     Sayali    1008   55000
3  Sanskruti    1004   60000
2      Veera    1003   80000
8     Smruti    1009   80000
9      Vijay    1010  100000

In [ ]:
df1.sort_values(by=["Salary"], ascending=False)

Emp Name  Emp id  Salary
9      Vijay    1010  100000
2      Veera    1003   80000
8     Smruti    1009   80000
3  Sanskruti    1004   60000
7     Sayali    1008   55000
4    Archana    1005   50000
1     Kartik    1002   40000
5   Aradhana    1006   30000
0    Ganesh     1001   25000
6    Pratham    1007   15000

In [ ]:
# Define a dictionary to store employee data
employees = {}

# Ask the user for the number of employees
num_employees = int(input("How many employees do you want to add? "))

# Loop through each employee and ask for their name and salary
for i in range(num_employees):
    name = input("Enter employee name: ")
    salary = float(input("Enter employee salary: "))
    employees[name] = salary

# Find the manager with the highest salary and the HR person with the second highest salary
sorted_salaries = sorted(employees.values(), reverse=True)
manager_salary = sorted_salaries[0]
hr_salary = sorted_salaries[1]

manager = ""
hr = ""

for name, salary in employees.items():
    if salary == manager_salary:
        manager = name
    elif salary == hr_salary:
        hr = name

# Calculate the total expenditure on employee salaries
total_expenditure = sum(employees.values())

# Display the results
print("Manager with highest salary: ", manager)
print("HR with second highest salary: ", hr)
print("Total expenditure on salaries: ", total_expenditure)

How many employees do you want to add? 5
Enter employee name: s
Enter employee salary: 1
Enter employee name: u
Enter employee salary: 2
Enter employee name: y
Enter employee salary: 3
Enter employee name: a
Enter employee salary: 4
Enter employee name: s
Enter employee salary: 5
Manager with highest salary:  s
HR with second highest salary:  a
Total expenditure on salaries:  14.0


In [ ]:
import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/sal.xlsx')
print(df.values.tolist())

[['Ganesh ', 1001, 25000], ['Kartik', 1002, 40000], ['Veera', 1003, 80000], ['Sanskruti', 1004, 60000], ['Archana', 1005, 50000], ['Aradhana', 1006, 30000], ['Pratham', 1007, 15000], ['Sayali', 1008, 55000], ['Smruti', 1009, 80000], ['Vijay', 1010, 100000]]


In [ ]:
#dictionary operations
dict1 = {"ABC":2742023, "EDF":89}
print(dict1)
print(dict1.keys())
print(dict1.values())
dict1.update({"SCE":8-9-2022})
print(dict1)
a = dict1.__len__()
print(a)
dict1.pop("SCE")
print(dict1)


{'ABC': 2742023, 'EDF': 89}
dict_keys(['ABC', 'EDF'])
dict_values([2742023, 89])
{'ABC': 2742023, 'EDF': 89, 'SCE': -2023}
3
{'ABC': 2742023, 'EDF': 89}


In [ ]:
#sales
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/csv')
print(df.values.tolist())

[['ms1001', 'item1', 100, 75, 30, 4500], ['ms1002', 'item2', 150, 100, 75, 3675], ['ms1003', 'item3', 200, 150, 100, 4567], ['ms1004', 'item4', 250, 200, 125, 7654], ['ms1005', 'item5', 300, 250, 150, 9876], ['ms1006', 'item6', 350, 300, 175, 3456], ['ms1007', 'item7', 400, 350, 200, 2345], ['ms1008', 'item8', 450, 400, 225, 8708], ['ms1009', 'item9', 500, 450, 250, 2345], ['ms1010', 'item10', 550, 500, 300, 7886], ['ms1011', 'item11', 600, 550, 350, 5647], ['ms1012', 'item12', 650, 600, 400, 9876], ['ms1013', 'item13', 700, 650, 450, 2854], ['ms1014', 'item14', 750, 700, 500, 9735], ['ms1015', 'item15', 800, 750, 550, 5247], ['ms1016', 'item16', 850, 800, 600, 8765], ['ms1017', 'item17', 900, 850, 650, 9467], ['ms1018', 'item18', 950, 900, 700, 2745], ['ms1019', 'item19', 1000, 950, 750, 9476], ['ms1020', 'item20', 1050, 1000, 800, 7489]]


In [ ]:
#supplier
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/EMT1579-1580.csv')
print(df.values.tolist())

[[100000069.0, 'A', 500062.0, 'E', 'India', nan, nan, nan, nan], [100000069.0, 'A', 503148.0, 'F', 'India', nan, nan, nan, nan], [100000069.0, 'A', 505962.0, 'G', 'India', nan, nan, nan, nan], [100000070.0, 'B', 512846.0, 'H', 'Germany', nan, nan, nan, nan], [100000070.0, 'B', 500305.0, 'I', 'India', nan, nan, nan, nan], [100000070.0, 'B', 519103.0, 'J', 'Japan', nan, nan, nan, nan], [100000070.0, 'B', 502520.0, 'K', 'Taiwan', nan, nan, nan, nan], [100000070.0, 'B', 536536.0, 'L', 'USA', nan, nan, nan, nan], [100000102.0, 'C', 505962.0, 'M', 'India', nan, nan, nan, nan], [100000102.0, 'C', 524767.0, 'N', 'Korea', nan, nan, nan, nan], [100000112.0, 'D', 504609.0, 'O', 'India', nan, nan, nan, nan], [100000112.0, 'D', 510821.0, 'P', 'Korea', nan, nan, nan, nan], [100000069.0, 'A', 500062.0, 'E', 'India', nan, nan, nan, nan], [100000069.0, 'A', 503148.0, 'F', 'India', nan, nan, nan, nan], [100000069.0, 'A', 500062.0, 'E', 'India', nan, nan, nan, nan], [100000069.0, 'A', 500062.0, 'E', 'Ind

In [ ]:
#set
s1={10,20,30}
for i in s1:
  print(s1)

{10, 20, 30}
{10, 20, 30}
{10, 20, 30}


In [ ]:
#add single element
s1 = {10,11,12}
s1.add(5)
print(s1)

{10, 11, 12, 5}


In [ ]:
#add multiple elements
s1 = {10,11,12}
s1.update((7,8,1))
print(s1)


{1, 7, 8, 10, 11, 12}


In [ ]:
#remove and discard
s1 = {2,3,4,6}
s1.discard(7)
print(s1)

{2, 3, 4, 6}


In [ ]:
#set union
t1={1,2,3,4,8}
t2={5,6,7,8}
c1=t1|t2
print(c1)

{1, 2, 3, 4, 5, 6, 7, 8}


In [ ]:
#intersection
i1=t1 & t2
print(i1)

{8}


In [ ]:
#set difference
i1= t1-t2
print(i1)

{1, 2, 3, 4}


In [ ]:
#symmetric difference
t1= {10,20,30,40,50,60,1,15,11,2003,12}
t2= {50,1,11,2003,60,70}
i1 = t1 ^ t2
print(i1)


{70, 40, 10, 12, 15, 20, 30}


In [ ]:
#null
s1 = {10,20,30,40}
s1.clear()
print(s1)

set()


In [ ]:
import datetime

def create_study_schedule(subjects, topics):
    today = datetime.datetime.today()
    schedule = {}

    for subject in subjects:
        schedule[subject] = []

        for topic in topics[subject]:
            study_date = today + datetime.timedelta(days=topics[subject][topic])
            schedule[subject].append((topic, study_date))

    return schedule

subjects = ['Math', 'Science', 'History']
topics = {
    'Math': {
        'Algebra': 2,
        'Geometry': 3,
        'Trigonometry': 4
    },
    'Science': {
        'Biology': 2,
        'Chemistry': 3,
        'Physics': 4
    },
    'History': {
        'World War II': 2,
        'Ancient Egypt': 3,
        'Renaissance': 4
    }
}

schedule = create_study_schedule(subjects, topics)

for subject in schedule:
    print(subject)
    for topic, study_date in schedule[subject]:
        print(f'- {topic}: {study_date.strftime("%m/%d/%Y")}')


Math
- Algebra: 04/29/2023
- Geometry: 04/30/2023
- Trigonometry: 05/01/2023
Science
- Biology: 04/29/2023
- Chemistry: 04/30/2023
- Physics: 05/01/2023
History
- World War II: 04/29/2023
- Ancient Egypt: 04/30/2023
- Renaissance: 05/01/2023


In [ ]:
def Loopoffruits():
  fruits = ["Apple","Banana","Cherry"]
  for i in fruits:
    print(i,"it is an fruit name")
Loopoffruits()


Apple it is an fruit name
Banana it is an fruit name
Cherry it is an fruit name


In [ ]:
print("Enter a value")
num =int(input())
sum=0
i=1
while i<=num:
  sum=sum+i
  i=i+1
  print("sum",sum)

In [ ]:
l1=[5,6,8,9,10,12,'A','B']
print(l1)

[5, 6, 8, 9, 10, 12, 'A', 'B']


In [ ]:
import csv
file=open("/content/drive/MyDrive/emp (2).csv","r")
data = list(csv.reader(file))
data.sort()
print(data)
file.close()
file1 = open("/content/drive/MyDrive/Emp_salary.csv","r")
data1 = list(csv.reader(file1))
print(data1)
#merging two files
data2=[]
for i in range(len(data)):
 data2.append(data[i]+data1[i])
print(data2)
print(data2[0])
#sorting as per records
data2.sort(key=lambda x: int(x[2]), reverse = True)
print(data2)
#converting list to csv file
file2 = open("/content/drive/MyDrive/csv","w")
cw=csv.writer(file2)
cw.writerows(data2)
file.close()
file1.close()
file3.close()

[['1', 'Sanvi', 'Manager', '100000'], ['2', 'Mrunmayee', 'Sr. Manager', '95000'], ['3', 'Jayesh', 'Manager', '80000'], ['4', 'Gouri', 'Sr. Manager', '95000'], ['5', 'Mahesh', 'Supervisor', '500000']]
[['ID', 'SALARY'], ['101', '57000'], ['102', '95000'], ['103', '85000'], ['104', '87000'], ['105', '63000'], ['106', '34000'], ['107', '75000'], ['108', '60000'], ['109', '45000'], ['110', '50000']]
[['1', 'Sanvi', 'Manager', '100000', 'ID', 'SALARY'], ['2', 'Mrunmayee', 'Sr. Manager', '95000', '101', '57000'], ['3', 'Jayesh', 'Manager', '80000', '102', '95000'], ['4', 'Gouri', 'Sr. Manager', '95000', '103', '85000'], ['5', 'Mahesh', 'Supervisor', '500000', '104', '87000']]
['1', 'Sanvi', 'Manager', '100000', 'ID', 'SALARY']


ValueError: ignored

In [ ]:
import pandas as pd
df = pd.read_excel('/content/drive/MyDrive/Emp.xlsx')
a = df
print(a.values.tolist())
df1= pd.read_excel(r'/content/drive/MyDrive/sal.xlsx')
l = list(df1.itertuples(index=False))

t1=[tuple(x)for x in df1.values]

d1=df.to_dict()
def freq(l):
    counter=0
    num=l[0]
    for i in l:
      cf = l.count(i)
      if(cf>counter):
        counter=cf
        num=i
        return 0
        print(freq(l))


[['Sr no.', 'Emp Name', 'Emp id', 'Date', 'Leaves'], [1, 'Ganesh ', 1001, datetime.datetime(2023, 1, 21, 0, 0), 2], [2, 'Kartik', 1002, datetime.datetime(2023, 1, 22, 0, 0), 4], [3, 'Veera', 1003, datetime.datetime(2023, 1, 23, 0, 0), 8], [4, 'Sanskruti', 1004, datetime.datetime(2023, 1, 24, 0, 0), 6], [5, 'Archana', 1005, datetime.datetime(2023, 1, 25, 0, 0), 1], [6, 'Aradhana', 1006, datetime.datetime(2023, 1, 26, 0, 0), 2], [7, 'Pratham', 1007, datetime.datetime(2023, 1, 27, 0, 0), 3], [8, 'Sayali', 1008, datetime.datetime(2023, 1, 28, 0, 0), 5], [9, 'Smruti', 1009, datetime.datetime(2023, 1, 29, 0, 0), 9], [10, 'Vijay', 1010, datetime.datetime(2023, 1, 30, 0, 0), 7]]


In [ ]:
# Arithmetic Operators
a = 10
b = 5
print(a + b) # Addition operator
print(a - b) # Subtraction operator
print(a * b) # Multiplication operator
print(a / b) # Division operator
print(a % b) # Modulo operator
print(a ** b) # Exponentiation operator
print(a // b) # Floor division operator

# Comparison Operators
print(a == b)
print(a != b)
print(a > b)
print(a < b)
print(a >= b)
print(a <= b)



# Bitwise Operators
p = 60
q = 13
print(p & q)
print(p | q)
print(p ^ q)
print(~p)
print(p << 2)
print(p >> 2)

# Assignment Operators
x = 5
x += 3 # x = x + 3
print(x)
x -= 3 # x = x - 3
print(x)
x *= 3 # x = x * 3
print(x)
x /= 3 # x = x / 3
print(x)
x %= 3 # x = x % 3
print(x)
x //= 3 # x = x // 3
print(x)
x **= 3 # x = x ** 3
print(x)



15
5
50
2.0
0
100000
2
False
True
True
False
True
False
12
61
49
-61
240
15
8
5
15
5.0
2.0
0.0
0.0


In [ ]:
budget = 500
item_cost = 166

vegetables_cost = int(input("Enter the cost of vegetables: "))
grocery_cost = int(input("Enter the cost of grocery: "))

if vegetables_cost + grocery_cost > budget:
    print("Aradhana cannot buy daily needs.")
else:
    if vegetables_cost == item_cost and grocery_cost == item_cost:
        print("Aradhana can buy all the items.")
    else:
        print("Aradhana cannot buy daily needs.")

Enter the cost of vegetables: 166
Enter the cost of grocery: 166
Aradhana can buy all the items.


In [ ]:
import pandas as pd
df1 = pd.read_excel('/content/drive/MyDrive/suyash cabyh.xlsx')
data = df1.values.tolist()
a = df1['chem']
b = df1['Name Of Students']
df1['chem'] = df1['chem'].astype('int64')
d = df1['Name Of Students'][df1['chem'] > 14]
def student(a, b, d):
    print('Name Of Students:', a, b)
student(a, b, d)
def student_marks(d):
    print('Student marks:', d)
student_marks(d)

Name Of Students: 0    12
1    10
2    11
3    20
4    12
5    12
6    16
7    17
8    20
Name: chem, dtype: int64 0       ayush
1      suyash
2      piyush
3     vidnesh
4    shreyash
5        yash
6      jayesh
7      kiresh
8     atharva
Name: Name Of Students, dtype: object
Student marks: 3    vidnesh
6     jayesh
7     kiresh
8    atharva
Name: Name Of Students, dtype: object


In [ ]:
import numpy as np
arr3 = np.array([0, 1, 2, 3, 4, 5])
print(arr3)


[0 1 2 3 4 5]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
sum_val = np.sum(arr)
mean_val = np.mean(arr)
print(sum_val)  # Output: 15
print(mean_val)  # Output: 3.0

15
3.0


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
max_val = np.max(arr)
min_val = np.min(arr)
print(max_val)  # Output: 5
print(min_val)  # Output: 1


5
1


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
transposed_arr = np.transpose(arr)
print(transposed_arr)  # Output: [[1 4]
                       #          [2 5]
                       #          [3 6]]


[[1 4]
 [2 5]
 [3 6]]


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
dot_product = np.dot(arr1, arr2)
print(dot_product)  # Output: 32


32


In [ ]:
import numpy as np

arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
result = arr1 + arr2
print(result)  # Output: [5 7 9]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr[2:4])  # Output: [3 4]


[3 4]


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])
reshaped_arr = arr.reshape(2, 3)
print(reshaped_arr)  # Output: [[1 2 3]
                     #          [4 5 6]]


[[1 2 3]
 [4 5 6]]


In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6]])
print(arr.shape)  # Output: (2, 3)


(2, 3)


In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])
print(arr)  # Output: [1 2 3 4 5]


[1 2 3 4 5]


In [ ]:
#Fetch all details for website
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/109_csv.csv')
filtered_df = df[df['Age'] >= 12]
print(filtered_df)


    Sr.No      Name               Mail Id  Phone Number   Age  Gender
0       1     suyash     suyash@gmail.com     9421516611   12    male
2       3     roshan     roshan@gmail.com     9423335166   18    male
3       4     tanmay     tanmay@gmail.com     9444215166   19    male
4       5    atharva    atharva@gmail.com     9424415166   20    male
5       6   prajakta   prajakta@gmail.com     9425515166   21  female
6       7  jayashree  jayashree@gmail.com     9421566166   12  female
7       8      essak      essak@gmail.com     9447215166   22    male
8       9      vipul      vipul@gmail.com     9427715166   55    male
9      10     aditya     aditya@gmail.com     9428815166   50    male
10     11     manasi     manasi@gmail.com     9499215166   42  female
11     12  vaishnavi  vaishnavi@gmail.com     9410215166   46  female
12     13     dipika     dipika@gmail.com     9420215166   82  female
14     15      kiran      kiran@gmail.com     9504215166   54    male
15     16      vijay

In [ ]:
#give special offer to all females
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/109_csv.csv')
female_users = df[df['Gender'] == 'Female']
for index, row in female_users.iterrows():
    phone_Number = row['Phone_Number']
    print(f"Special offer applied to female user with user_id: {phone_Number}")

In [ ]:
#Fetch all details of male convert them into list
import pandas as pd
df = pd.read_csv('/content/drive/MyDrive/109_csv.csv')
male_users = df[df['Gender'] == 'male']
male_user_list = male_users.values.tolist()
for row in male_user_list:
    print(row)


In [ ]:
#Operation 1 on list
male_user_count = len(male_user_list)
print("Number of male users:", male_user_count)

In [ ]:
#Operation 2 on list
to_do_list = []
for row in male_user_list:
    phone_number = row[3]
    to_do_list.append(phone_number)
print(" Phone Numbers of all males :")
for phone_number in to_do_list:
    print(phone_number)

In [ ]:
#Operation 3 on list
to_do_list = []
for row in male_user_list:
    phone_number = row[2]
    to_do_list.append(phone_number)
print("Email of all males :")
for Email_id in to_do_list:
    print(Email_id)

In [ ]:
#Operation 4 on list
phone_numbers = [row[3] for row in male_user_list]
repeated_digits = []
for number in phone_numbers:
    digits = [int(digit) for digit in str(number) if digit.isdigit()]
    unique_digits = set(digits)
    repeated_digits.extend([digit for digit in unique_digits if digits.count(digit) > 1])
print("Repeated digits in phone numbers:")
for digit in repeated_digits:
    print(digit)

In [ ]:
# Define a dictionary to store employee data
employees = {}

# Ask the user for the number of employees
num_employees = int(input("How many employees do you want to add? "))

# Loop through each employee and ask for their name and salary
for i in range(num_employees):
    name = input("Enter employee name: ")
    salary = float(input("Enter employee salary: "))
    employees[name] = salary

# Find the manager with the highest salary and the HR person with the second highest salary
sorted_salaries = sorted(employees.values(), reverse=True)
manager_salary = sorted_salaries[0]
hr_salary = sorted_salaries[1]

manager = ""
hr = ""

for name, salary in employees.items():
    if salary == manager_salary:
        manager = name
    elif salary == hr_salary:
        hr = name

# Calculate the total expenditure on employee salaries
total_expenditure = sum(employees.values())

# Display the results
print("Manager with highest salary: ", manager)
print("HR with second highest salary: ", hr)
print("Total expenditure on salaries: ", total_expenditure)